language: generic
sudo: required
services:
          - docker

before_install:
          - docker build -t guptakapil/docker-react -f Dockerfile.dev .

script:
          - docker run -e CI=true guptakapil/docker-react npm run test
