language: generic
sudo: required
services:
          - docker

before_install:
          - docker build -t guptakapil/docker-react -f Dockerfile.dev .

script:
          - docker run -e CI=true guptakapil/docker-react npm run test

deploy:
          provider: elasticbeanstalk
          region: "ap-south-1"
          app: "docker-react"
          env: "DockerReact-env"
          bucket-name: "elasticbeanstalk-ap-south-1-028920302411"
          bucker-path: "docker-react"
          on:
                branch: "master"
          access_key_id: "AKIAQNO6IZNFUWXVHKFQ"
          secret_access_key: "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"
